[project]
name = "datasci-mindmap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.45.1",
    "streamlit-tts>=0.0.7",
]
